-- Treesitter!
return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    require('nvim-treesitter').install({
      'bash',
      'c',
      'css',
      'dockerfile',
      'fish',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'html',
      'javascript',
      'json',
      'lua',
      'make',
      'markdown',
      'python',
      'ruby',
      'rust',
      'sql',
      'svelte',
      'terraform',
      'toml',
      'tsx',
      'typescript',
      'typst',
      'vim',
      'yaml',
      'zig',
      'zsh',
    })
  end,
}
